MUCodeAcademy/react-battle-c7

index.js
Adds server boilerplate including: 
- Defaults to port 8080
- Sets up serving of static files
- Sets up `dotenv` configuration
- Sets up usage of JSONs via express
=> adds boilerplate for server

index.js, server/models/user.models.js, server/routes/user.routes.js
- adds app.use to index.js for route: /api/users
- sets up login routes in user.routes.js
- sets up login models in user.models.js
=> Login routing

index.js, server/config/pg.conf.js, server/models/user.models.js
- changes user to users.row[0] in login model
- changes users to users.rows.length in signup model
- makes both signup and login work as intended
=> Pgconf debug

src/App.css, src/components/GamePage/components/Board.js, src/components/GamePage/components/Cell.js
Adds Cell
Cell changes colors based off the values passed in.
Values:
- Ship: boolean - Whether or not a ship lives in this coordinate
- Player: boolean - Whether or not the cell belongs to the player board
- Hit: boolean - Whether or not the cell has been selected for a hit
- Coordinate: String - The coordinate of the cell ("a1")
Co-authored-by: DarcyJorgensen <DarcyJorgensen@users.noreply.github.com>
Co-authored-by: trevorrjacobson <trevorrjacobson@users.noreply.github.com>
=> Added cell component, changes colors based on vals

src/App.css, src/components/GamePage/components/Board.js
Maps through an array to make a board.
Each element in the array contains {ship: boolean, hit: boolean, player: boolean, coordinate: string};
=> Adds board logic

src/App.css, src/App.js, src/components/About.js, src/components/GamePage/components/Chat.js, src/components/WaitingRoom.js, src/shared/hooks/useSocket.js
Connects useSocket and Chat
Adds routing from waiting room to gamepage
=> Connect chat to socket

src/components/LoginPage.js, src/components/SignupPage.js
Fixes bugs:
- Error messages now adjust onBlur instead of when the button is pressed.
- Red color no longer breaks the login page.
- Backend error messages now disappear (and reappear if necessary) when the button is pressed again.
=> Fixes bugs with color and error messages

src/App.css, src/components/About.js, src/components/GamePage/GamePage.js, src/components/GamePage/components/ScoreBoard.js
Adds scoreboard and gamepage styling
=> Scoreboard

index.js, src/components/GamePage/GamePage.js, src/components/GamePage/components/ScoreBoard.js, src/components/LoginPage.js, src/components/SignupPage.js, src/components/WaitingRoom.js, src/shared/hooks/useSocket.js
Bugfixes addressed:
- Add prevent default to join room button in waiting room to prevent page refreshing.
- Adds text to Game Page to display curr room.
- Removes spread operator from joinRoom function to fix username error in chat comp
- Adds placeholders to login and signup page text fields.
- Corrects login error functionality.
=> Bugfix monday week2

src/shared/hooks/useSocket.js
Adds functionality to the sendGuess and sendBoatsReady socket functions and listeners. Brings in data from GameContext.
=> adds functionality to socket events

index.js, src/components/GamePage/GamePage.js, src/components/GamePage/components/Board.js, src/components/GamePage/components/Cell.js, src/components/GamePage/components/ScoreBoard.js, src/shared/context/GameContext.js, src/shared/hooks/useSocket.js
Fixes bugs such as:
-Winning on first hit.
-Select not firing correctly.
-newGuess error tree and loser modal.
-Changing ready to userBoatsReady
=> Game mplementation bug fix

src/components/WaitingRoom.js, src/shared/context/GameContext.js
- Fixes being able to place boats after the board is reset.
- Makes it so game data is cleared when you enter the waiting room after playing a game.
=> Reset waiting room

src/App.css, src/components/GamePage/GamePage.js, src/components/GamePage/components/Cell.js, src/components/GamePage/components/ScoreBoard.js, src/shared/context/GameContext.js, src/shared/hooks/useSocket.js
Reverts MUCodeAcademy/react-battle-c7#32
=> Revert "Place ships"

src/components/WaitingRoom.js
- If you enter a room number to join, you can now press enter to join that room.
=> pressing enter after typing room num takes to room

index.js, src/App.css, src/components/GamePage/GamePage.js, src/components/GamePage/components/Cell.js, src/components/GamePage/components/ScoreBoard.js, src/shared/context/GameContext.js, src/shared/hooks/useSocket.js
Adds previously lost code
Adds  ship sinking functionality
=> Sinking ships function

src/App.css, src/components/GamePage/components/Chat.js, src/shared/hooks/useSocket.js
Adds new chat messages to the bottom and auto scrolls as they appear
=> Chat bottom

index.js, src/components/GamePage/components/Chat.js, src/shared/hooks/useSocket.js
- Gives a message to user in chat if opponent leaves game
- Adds a timestamp to all chat messages and player join/disconnect messages
=> Leave room message

index.js, src/components/GamePage/GamePage.js, src/components/GamePage/components/ScoreBoard.js, src/shared/context/GameContext.js, src/shared/hooks/useSocket.js
Changes boat display at top of screen when a boat has sunk.
Sends out chat message when a boat has sunk.
=> Display ships sunk

src/App.js, src/shared/context/UserContext.js
Alters logout function in UserContext to call logout api route and clear cookies.
=> adds api call to logout route for logout function

src/App.js
Adds loading state to App.js and conditionally renders components based on loading state. Loading is default at true and set to false after attempting validate call.
=> adds loading component and state

src/components/GamePage/components/ScoreBoard.js
Scoreboard starting state reflects current game status
=> Ships now stay sunk

src/components/GamePage/GamePage.js
mixes Modal console error messages
=> Modal bugfixes

src/App.js, src/components/About.js, src/components/GamePage/GamePage.js, src/components/GamePage/components/Board.js, src/components/GamePage/components/ScoreBoard.js, src/components/Navibar.js, src/shared/hooks/useSocket.js
cleaned up unused code and files
=> cleaned up unused code

public/index.html, src/App.css, src/components/About.js, src/components/LoginPage.js, src/components/Navibar.js, src/components/SignupPage.js
=> Style clean up

src/App.css, src/components/About.js
first sentence on about page a little larger than rest of the text and spacing from that sentence to rest of text (distinct)
=> made first sentence larger and spacing

src/shared/context/UserContext.js
Alters the signup function from User Context to run a login API call and create a cookie if signup is successful.
=> alters singup function to login after success

src/App.css, src/components/GamePage/GamePage.js, src/components/GamePage/components/Chat.js, src/components/GamePage/components/ScoreBoard.js
Centers Orientation button ad boat representation
Fix scroll changes 
Cleans up Chat box
=> Gamepage styling fixes
